import axios from "axios";
import moment from "moment";
const config = {
	//	basic_url: "http://d9-test.kksa",
	basic_url: "http://wb-horizon.kksa",
	/* *
	 * @params {string} urlRequest
	 */
	async load(urlRequest) {
		try {
			const response = await axios.get(this.basic_url + urlRequest);
			console.log(response);
			if (response.data) {
				return response.data;
			}
			return response;
		} catch (error) {
			console.error(error);
			return error;
		}
	},
	/**
	 * @params {string} url
	 */
	async datas() {
		//let datas = await this.load(url);
		let datas = this.defaultDatas;
		return datas;
	},
	/**
	 *
	 * @params {Array} jours
	 *  Supprimes les jours dépassées du tableau
	 */
	async formatValidDay(jours) {
		let newtableau = [];
		//let today = moment().format("ddd D MMM");
		//	let timestapToday = moment(today);
		if (jours && jours.length) {
			newtableau = jours.filter((jour) => {
				//let timestapDay = moment(jour.value);
				console.log(
					"timestapDay",
					jour.value,
					"---",
					moment().isSameOrBefore(jour.value)
				);
				//if (timestapDay >= timestapToday) {
				return jour;
				//	}
			});
		}
		return newtableau;
	},

	defaultDatas: {
		jours: [
			{
				label: "Fri.<br>2 Sep",
				value: "Fri 2 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sat.<br>3 Sep",
				value: "Sat 3 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sun.<br>4 Sep",
				value: "Sun 4 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Mon.<br>5 Sep",
				value: "Mon 5 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Tue.<br>6 Sep",
				value: "Tue 6 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Wed.<br>7 Sep",
				value: "Wed 7 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Thu.<br>8 Sep",
				value: "Thu 8 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Fri.<br>9 Sep",
				value: "Fri 9 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sat.<br>10 Sep",
				value: "Sat 10 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sun.<br>11 Sep",
				value: "Sun 11 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Mon.<br>12 Sep",
				value: "Mon 12 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Tue.<br>13 Sep",
				value: "Tue 13 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Wed.<br>14 Sep",
				value: "Wed 14 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Thu.<br>15 Sep",
				value: "Thu 15 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Fri.<br>16 Sep",
				value: "Fri 16 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sat.<br>17 Sep",
				value: "Sat 17 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sun.<br>18 Sep",
				value: "Sun 18 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Mon.<br>19 Sep",
				value: "Mon 19 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Tue.<br>20 Sep",
				value: "Tue 20 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Wed.<br>21 Sep",
				value: "Wed 21 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Thu.<br>22 Sep",
				value: "Thu 22 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Fri.<br>23 Sep",
				value: "Fri 23 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sat.<br>24 Sep",
				value: "Sat 24 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sun.<br>25 Sep",
				value: "Sun 25 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Mon.<br>26 Sep",
				value: "Mon 26 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Tue.<br>27 Sep",
				value: "Tue 27 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Wed.<br>28 Sep",
				value: "Wed 28 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Thu.<br>29 Sep",
				value: "Thu 29 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Fri.<br>30 Sep",
				value: "Fri 30 Sep 2022",
				creneau: [
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sat.<br>1 Oct",
				value: "Sat 1 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sun.<br>2 Oct",
				value: "Sun 2 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Mon.<br>3 Oct",
				value: "Mon 3 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Tue.<br>4 Oct",
				value: "Tue 4 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Wed.<br>5 Oct",
				value: "Wed 5 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Thu.<br>6 Oct",
				value: "Thu 6 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Fri.<br>7 Oct",
				value: "Fri 7 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Vendredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sat.<br>8 Oct",
				value: "Sat 8 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Samedi",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Sun.<br>9 Oct",
				value: "Sun 9 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Dimanche",
							status: 0,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Mon.<br>10 Oct",
				value: "Mon 10 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Lundi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Tue.<br>11 Oct",
				value: "Tue 11 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mardi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Wed.<br>12 Oct",
				value: "Wed 12 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Mercredi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
			{
				label: "Thu.<br>13 Oct",
				value: "Thu 13 Oct 2022",
				creneau: [
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "07:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "08:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "09:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "10:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "11:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "12:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "13:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "14:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "15:00",
					},
					{
						conf: {
							label: "Jeudi",
							status: 1,
							h_d: "7",
							m_d: "00",
							h_f: "17",
							m_f: "00",
						},
						value: "16:00",
					},
				],
			},
		],
		entityType: {
			uuid: "6c63c1e5-74b8-4228-87a8-3422272236cc",
			langcode: "fr",
			status: true,
			dependencies: [],
			id: "node_coiffure_homme_263",
			label: "Pididi (node.coiffure_homme)",
			jours: [
				{
					label: "Dimanche",
					status: 0,
					h_d: "7",
					m_d: "00",
					h_f: "17",
					m_f: "00",
				},
				{
					label: "Lundi",
					status: 1,
					h_d: "7",
					m_d: "00",
					h_f: "17",
					m_f: "00",
				},
				{
					label: "Mardi",
					status: 1,
					h_d: "7",
					m_d: "00",
					h_f: "17",
					m_f: "00",
				},
				{
					label: "Mercredi",
					status: 1,
					h_d: "7",
					m_d: "00",
					h_f: "17",
					m_f: "00",
				},
				{
					label: "Jeudi",
					status: 1,
					h_d: "7",
					m_d: "00",
					h_f: "17",
					m_f: "00",
				},
				{
					label: "Vendredi",
					status: 1,
					h_d: "7",
					m_d: "00",
					h_f: "17",
					m_f: "00",
				},
				{
					label: "Samedi",
					status: 0,
					h_d: "7",
					m_d: "00",
					h_f: "17",
					m_f: "00",
				},
			],
			disabled_dates: [],
			disabled_periode: [],
			interval: "60",
			decallage: "0",
			number_week: 6,
		},
	},
};
export default config;
